In [2]:
import numpy as np
a=np.floor(10*np.random.random((3,4)))
print(a)

[[9. 9. 4. 3.]
 [3. 1. 9. 4.]
 [8. 3. 8. 9.]]


In [3]:
print(a.ravel())
#拉直矩阵

[9. 9. 4. 3. 3. 1. 9. 4. 8. 3. 8. 9.]


In [4]:
a.reshape(2,-1)
#不知道多少列直接用-1替代

array([[9., 9., 4., 3., 3., 1.],
       [9., 4., 8., 3., 8., 9.]])